### ISSUE TITLE
Inactive URI

### ISSUE THREAD

**Issue by Naeima** [rdmpage/bbc-wildlife#1]
Hi, 
I am adopting your ontology into ours (https://naeima.github.io/foo_html/), I wonder why the ontology URL (http://purl.org/ontology/wo/ ) is inactive (404 Not Found). 
Thanks,
Naeima

**Comment by rdmpage** [comment]
Hi @Naeima,

Please note that the ontology isn't mine, it's the BBC's. For some background see [Blue Planet II, the BBC, and the Semantic Web: a tale of lessons forgotten and opportunities lost](https://iphylo.blogspot.com/2017/12/blue-planet-ii-bbc-and-semantic-web.html) which gives some background into why the BBC's project died. 

If you do a bit of sleuthing with the URL (i.e., follow the redirects) and play with the Wayback machine you'll get to some archived versions, e.g.: https://web.archive.org/web/20160823033612/http://www.bbc.co.uk/ontologies/wo/ 

I also archived a copy in this repo.

Hope this helps.

**Comment by Naeima** [comment]
Hi,

Thank you so much for this! very helpful tip.

Best regards,
Naeima
________________________________
